# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: maven build

on:
  push:
    branches: [ setup-ghactions, unit-test-creation ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
        node: ['11', '14']

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B install --file pom.xml
      
    - name: Check with PMD
      run: mvn pmd:pmd --file pom.xml
      
    - name: jacoco-badge-generator
      uses: cicirello/jacoco-badge-generator@v2.2.1
      with:
        generate-coverage-badge: true
        generate-branches-badge: true
        jacoco-csv-file: core/target/site/jacoco/jacoco.csv
        
    - name: Commit and push the badge (if it changed)
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'commit badge'
        add: '*.svg'

    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: core/target/site/jacoco/

    - name: Upload PMD report
      uses: actions/upload-artifact@v2
      with:
        name: pmd-report
        path: core/target/site/pmd.html

    - name: Upload jar with dependencys
      uses: actions/upload-artifact@v2
      with:
        name: pmdungeon
        path: desktop/target/pmdungeon-desktop-jar-with-dependencies.jar
