# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: maven build

on:
  push:
    branches: [ setup-ghactions ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: jacoco-badge-generator
      uses: cicirello/jacoco-badge-generator@v2.2.1
      with:
        generate-coverage-badge: true
        generate-branches-badge: true
        jacoco-csv-file: core/target/site/jacoco/jacoco.csv
